billie2: Fix CONFIG_DEBUG_FS
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
For kernel requirements at matrix level 5, Kernel config errors:
    For config CONFIG_DEBUG_FS, value = y but required n
For kernel requirements at matrix level 6, Kernel config errors:
    For config CONFIG_DEBUG_FS, value = y but required n